version: 2
jobs:
  build:
    working_directory: ~/jest-change-matchers
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore-cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save-cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: |
            yarn ci
  npm:
    working_directory: ~/jest-change-matchers
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Load npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: |
            npm publish
workflows:
  version: 2
  build-deploy:
    jobs:
      - build